landing_page_homepage:
    path:     /
    defaults: { _controller: LandingPageBundle:Default:index }

prueba_producto1:
    path:     /producto1/{id}
    defaults: { _controller: LandingPageBundle:Default:producto1 }
